spring.datasource.url=jdbc:postgresql://localhost:5432/library_management
spring.datasource.username=lms_user
spring.datasource.password=lms_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

logging.level.org.springframework.security=DEBUG